import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import companyRoutes from './company.routes';
import coaRoutes from './coa.routes';
import transactionRoutes from './transaction.routes';
import voucherRoutes from './voucher.routes';
import journalRoutes from './journal.routes';
import customerRoutes from './customer.routes';
import supplierRoutes from './supplier.routes';
import paymentRoutes from './payment.routes';
import inventoryRoutes from './inventory.routes';
import fixedAssetRoutes from './fixedAsset.routes';
import taxRoutes from './tax.routes';
import reportRoutes from './report.routes';
import costCenterRoutes from './costCenter.routes';
import profitCenterRoutes from './profitCenter.routes';
import budgetRoutes from './budget.routes';
import approvalRoutes from './approval.routes';
import recurringRoutes from './recurring.routes';
import documentRoutes from './document.routes';
import auditRoutes from './audit.routes';
import dashboardRoutes from './dashboard.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/companies', companyRoutes);
router.use('/coa', coaRoutes);
router.use('/transactions', transactionRoutes);
router.use('/vouchers', voucherRoutes);
router.use('/journals', journalRoutes);
router.use('/customers', customerRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/payments', paymentRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/fixed-assets', fixedAssetRoutes);
router.use('/taxes', taxRoutes);
router.use('/reports', reportRoutes);
router.use('/cost-centers', costCenterRoutes);
router.use('/profit-centers', profitCenterRoutes);
router.use('/budgets', budgetRoutes);
router.use('/approvals', approvalRoutes);
router.use('/recurring', recurringRoutes);
router.use('/documents', documentRoutes);
router.use('/audit', auditRoutes);
router.use('/dashboard', dashboardRoutes);

export default router;
